FROM tomcat:9.0.85-jdk17-temurin

# Optional timezone
ENV TZ=UTC


RUN cp -r /usr/local/tomcat/webapps.dist/* /usr/local/tomcat/webapps/

# Custom user config
COPY ./tomcat-conf/tomcat-users.xml /usr/local/tomcat/conf/tomcat-users.xml

# Remove IP restrictions from manager context
COPY ./tomcat-manager-context/context.xml /usr/local/tomcat/webapps/manager/META-INF/context.xml
